export const environment = {
  production: false,
  defaultLang: 'en',
  i18n: {
    en: {
      appNamePrefix: 'Mine',
      appNameSuffix: 'sweeper',
      enterInstance: 'Enter Instance',
      density: 'Density',
      bestScore: 'Best Score',
      bestTime: 'Best Time',
      newRecord: 'New Record!',
      highScoreUnlocked: 'High Score',
      achievementUnlocked: 'ACHIEVEMENT UNLOCKED!',
      plusOneDay: '+1 day',
      plusDays: '+{days} days',
      scoreMessage: '{message}. Your score was {score}',
      descriptions: {
        'Super Easy': '9 x 9 Board with 10 mines',
        Easy: '10 x 10 Board with 15 mines',
        Bathrooms: '16 x 9 Board. Ideal for playing on mobile',
        Medium: '16 x 16 Board with 40 mines',
        Hard: '16 x 30 Board with 99 mines',
        Tryhard: '20 x 24 Board with 168 mines',
        Random: 'Totally random size and mines',
        Hobby: 'Casual random matches to pass the time',
        'No Flags': '13 x 33 Board with 60 mines without flags',
        'Hobby Static': '13 x 33 Board with 60',
      },
      lossMessages: [
        'Game Over!',
        'Bad luck, try again.',
        'You stepped on a mine!',
        'Better luck next time.',
        'Boom! Try one more time.',
      ],
      winMessages: [
        'Victory!',
        'Great job!',
        'You cleared the minefield!',
        'Unstoppable!',
        'Flawless execution!',
      ],
      credits: 'credits',
      tacticalRevert: 'Tactical Revert',
      revertDescription: 'A mine is about to explode! Use your revert to bypass the blast.',
      reverseLeft: 'Reverts Left:',
      continueGame: 'Continue Game',
      giveUp: 'Give Up',
    },
    es: {
      appNamePrefix: 'Busca',
      appNameSuffix: 'minitas',
      enterInstance: 'Entrar al Campo Minado',
      density: 'Densidad',
      bestScore: 'Mejor Puntaje',
      bestTime: 'Mejor Tiempo',
      newRecord: '¡Nuevo récord!',
      highScoreUnlocked: 'Nueva puntuación máxima',
      achievementUnlocked: '¡LOGRO DESBLOQUEADO!',
      plusOneDay: '+1 día',
      plusDays: '+{days} días',
      scoreMessage: '{message}. Tu puntaje fue de {score}',
      descriptions: {
        'Super Easy': 'Tablero 9 x 9 con 10 minas',
        Easy: 'Tablero 10 x 10 con 15 minas',
        Bathrooms: 'Tablero de 16x9. Ideal para pasar el rato en el celular',
        Medium: 'Tablero 16 x 16 con 40 minas',
        Hard: 'Tablero 16 x 30 con 99 minas',
        Tryhard: 'Tablero 20 x 24 con 168 minas',
        Random: 'Tamaño y minas totalmente aleatorios',
        Hobby: 'Partidas casuales y aleatorias para pasar el rato',
        'No Flags': 'Tablero 13 x 33 con 60 minas sin poder usar banderas',
        'Hobby Static': 'Tablero 13 x 33 con 60 minas',
      },
      lossMessages: ['¡Fin del juego!', 'Mala suerte'],
      winMessages: ['¡Victoria!', '¡Excelente trabajo!'],
      credits: 'creditos',
      tacticalRevert: 'Reversión Táctica',
      revertDescription:
        '¡Una mina está a punto de explotar! Usa un reintento para evitar la detonación.',
      reverseLeft: 'Reintentos restantes:',
      continueGame: 'Continuar Partida',
      giveUp: 'Rendirme',
    },
  },
};
